### ISSUE TITLE
erro when run mashr_flashr_workflow.ipynb

### ISSUE THREAD

**Issue by zpliu1126** [stephenslab/gtexresults#11]
Hi~ Gao Wang,
  I organized the test data (./data/fastqtl) into the input format required by mashr according the `fastqtl_to_mash.ipynb` and successfully got the `*rds` file.

Then I followed the tutorial to run the following command

```bash
%use Bash 
module load GSL/2.4
inputPath='./workflows/fastqtl_to_mash_output'
sos run mashr_flashr_workflow.ipynb mash -j 8 --data ${inputPath}/FastQTLSumStats.mash.rds
```
program outPut looks like that
```bash
INFO: Running vhat_mle: V estimate: "mle" method
INFO: Running flash_nonneg: Perform FLASH analysis with non-negative factor constraint (time estimate: 20min)
ERROR: flash_nonneg (id=8f1855b7521d395d) returns an error.
INFO: Running flash: Perform FLASH analysis with non-negative factor constraint (time estimate: 20min)
ERROR: flash (id=d284ee158551a142) returns an error.
INFO: Running pca: 
ERROR: pca (id=a23e3353e2a55ba7) returns an error.
```
In the log file `FastQTLSumStats.mash.flash.stderr`, it told me some things error with mashr
```bash
Error: 'cov_flash' is not an exported object from 'namespace:mashr'
Execution halted
```
I wonder that is the reason for the mashr version？This is the version of  mashr in my machine.

```bash
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /public/home/software/opt/bio/software/R/3.6.0/lib64/R/lib/libRblas.so
LAPACK: /public/home/software/opt/bio/software/R/3.6.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mashr_0.2.38 ashr_2.2-47 

loaded via a namespace (and not attached):
 [1] compiler_3.6.0   plyr_1.8.6       assertthat_0.2.1 Matrix_1.3-2    
 [5] abind_1.4-5      mixsqp_0.3-43    Rcpp_1.0.6       mvtnorm_1.1-1   
 [9] rmeta_3.0        SQUAREM_2021.1   grid_3.6.0       truncnorm_1.0-8 
[13] irlba_2.3.3      invgamma_1.1     lattice_0.20-41 
```

**Comment by gaow** [comment]
@zpliu1126 Please update to the current `master` on github for `mashr`, `ebnm` and `flashr` packages, all available at https://github.com/stephenslab This docker configuration should give you the exact version that works at this point you can install using these commits IDs as well:

https://github.com/stephenslab/gtexresults/blob/6e314acbe56c41387e3edd2961fe5517578c0789/workflows/mash.dockerfile#L36

(codes after this line are relevant to the software upgrades)

**Comment by zpliu1126** [comment]
Thanks for your quick replay.

I will to have a try.

**Comment by zpliu1126** [comment]
@gaow 
When entering the workflow for  pca, it went wrong again.

```bash
#FastQTLSumStats.mash.pca.stderr
Error: npc not less than or equal to n_conditions(data)
Execution halted
```
Is it due to the small amount of data in the test data set? 
I find there have only 4 geneId in two tissues.
```bash
#FastQTLSumStats.portable.log 
4 out of 8 groups extracted!
```

**Comment by gaow** [comment]
@zpliu1126 default number of PC is 3 in the pipeline. The test data has two groups I believe. You can use `--npc` to set it to eg 1 PC via `--npc 1` and see it work -- again this is a toy example and in practice it is up to your discretion how you want to handle it. There is also an option to not use PCA at all, eg set `--mixture-components flash flash_nonneg` to exclude PCA.

**Comment by zpliu1126** [comment]
I completed the whole workflow, thank you for your patience.
