### ISSUE TITLE
Compute MASH posteriors

### ISSUE THREAD

**Issue by zpliu1126** [stephenslab/gtexresults#12]
Hi~
I used the notebook [mashr_flashr_workflow.ipynb](https://github.com/stephenslab/gtexresults/blob/0b80fd00ddee548aac38a3a12faecd548f7730af/workflows/mashr_flashr_workflow.ipynb) to Compute MASH posteriors of eQTLs. But it assumed one eQTL per gene and applied the model learned above to those SNPs.
And I want to apply the mashR model to all significant lead eQTLs, in other words there may be, multiple eQTL per gene. The [page](https://stephenslab.github.io/gtex-eqtls/analysis/Independent_eQTL_Results.html#Format-conversion-pipeline-12) link to the  notebook [Independent_eQTL_Results.ipynb](https://github.com/gaow/mnm-gtex-v8/commit/7b5baab45254850a4729e0f0204b32f68893a43a) is outdated.  Can you provide the latest link to this notebook.

**Comment by gaow** [comment]
@zpliu1126 indeed we have updated that link in the current workflow notebook:

https://github.com/stephenslab/gtexresults/blob/master/workflows/mashr_flashr_workflow.ipynb

It seems you are on an earlier version of it. It is recommended that you check out the current version as well as the docker image. There are updates on supporting packages such as flashr and ebnm to fix errors reported by some other users, in case it is relevant to you.
