### ISSUE TITLE
Compute MASH posteriors

### ISSUE THREAD

**Issue by yueming-hu** [stephenslab/gtexresults#14]
Hi, @gaow 

Thanks for the great workflow.
I used the notebook [mashr_flashr_workflow.ipynb](http://stephenslab.github.io/gtex-eqtls/analysis/mashr_flashr_workflow.html) to Compute MASH posteriors of eQTLs. But it assumed one eQTL per gene and applied the model learned above to those SNPs.

And I want to apply the mashR model to all DAP-G fine-mapping group independent eQTL data. I want to convert it to MASH input format in order to compute posterior by Independent_eQTL_Results.ipynb. But the page link to the notebook [Independent_eQTL_Results.ipynb](http://stephenslab.github.io/gtex-eqtls/analysis/Independent_eQTL_Results.html) is outdated. Can you provide the latest link to this notebook? Or can you tell me a new conversion method?

Thanks

**Comment by gaow** [comment]
@yueming-hu sorry about that. I just fixed the link at the bottom of that HTML page you referred to above. I'll close this issue for now.

**Comment by yueming-hu** [comment]
@gaow Thank you for your prompt reply. After I tried your updated link, it still couldn't be opened, showing "This is not the web page you are looking for". Can you check the reason or send it to me directly?

**Comment by gaow** [comment]
@yueming-hu oops try again -- it should be visible now.

**Comment by yueming-hu** [comment]
It's OK now. Thanks!
