### ISSUE TITLE
FastQTL to mash

### ISSUE THREAD

**Issue by rmccoy7541** [stephenslab/gtexresults#5]
Hello, I am wondering about your code to convert FastQTL results to mash format. According to the FastQTL documentation, the output columns for nominal pass are:

1) ID of the tested molecular phenotype (in this particular case, the gene ID)
2) ID of the tested variant (in this case a SNP)
3) Distance between the variant and the phenotype in bp
4) The nominal p-value of association
5) The slope associated with the nominal p-value of association [only in version > v2-184]

and for permutation pass are:

1) ID of the tested molecular phenotype (in this particular case, the gene ID)
2) Number of variants tested in cis for this phenotype
3) MLE of the shape1 parameter of the Beta distribution
4) MLE of the shape2 parameter of the Beta distribution
5) Dummy [To be described later]
6) ID of the best variant found for this molecular phenotypes (i.e. with the smallest p-value)
7) Distance between the molecular phenotype - variant pair
8) The nominal p-value of association that quantifies how significant from 0, the regression coefficient is
9) The slope associated with the nominal p-value of association [only in version > v2-184]
10) A first permutation p-value directly obtained from the permutations with the direct method. This is basically a corrected version of the nominal p-value that accounts for the fact that multiple variants are tested per molecular phenotype.
11) A second permutation p-value obtained via beta approximation. We advice to use this one in any downstream analysis.

But the columns mentioned by your documentation are:

1) gene_id 
2) variant_id      
3) tss_distance    
4) ma_samples      
5) ma_count        
6) maf     
7) pval_nominal    
8) slope   
9) slope_se

Where did you find a standard error in the FastQTL results? Is it from a different version of the software? Thanks!

**Comment by gaow** [comment]
@rmccoy7541 truthfully we've not ran `fastqtl` by ourselves. The GTEx data we were provided (also available now on GTEx portal I believe) were said to come from `fastqtl` but were in the format documented in our documentation. Could you confirm that the actual fastqtl output does not have standard error?

If we assume `bhat/se(bhat)` follows a standard normal distribution then knowing `bhat` and `pval` should give us standard error. I guess I can allow for an input without standard error and compute that on the fly?

**Comment by gaow** [comment]
@rmccoy7541 I just downloaded the current  version of `fastqtl` (v2.165) and confirmed it does not have standard error. I'll do what I proposed above, update the documentation and make a new docker release for you to use. How does that sound? I'll try to do it later this evening.

**Comment by rmccoy7541** [comment]
Sounds great, and please take your time. Thanks.

**Comment by gaow** [comment]
@rmccoy7541 implemented in patch above as discussed. The documentation part of the workflow is also updated. I realize there is no need to update the `docker` because apparently the `scipy` module used to compute `se(bhat)` was already in the docker image (possibly due to module `tables` dependency). Anyways, you should be able to pull the code and add `--cols A B` to make it work, where A is column number for bhat, B is column number for p-value. Please let me know if there is still an issue.

**Comment by rmccoy7541** [comment]
Thanks!
