### ISSUE TITLE
concat() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by Zepeng-Mu** [stephenslab/gtexresults#6]
Hi,
I am running `fastqtl_to_mash.ipynb convert` and got this error:

```
INFO: Running convert_2: Merge single study data to multivariate data
Traceback (most recent call last):
  File "/tmp/jobs/61195873/tmpgrikchmr.py", line 303, in <module>
    if ssm.merge() == 0:
  File "/tmp/jobs/61195873/tmpgrikchmr.py", line 203, in merge
    ) for tissue in sorted(data.keys())], sort=True, axis = 1)
TypeError: concat() got an unexpected keyword argument 'sort'
ERROR: [convert_2]: [convert_2]:
Failed to execute python3 .sos/convert_2_0_1eb61b31.py
```

I think I did not encounter this error before.

Thanks in advance!

**Comment by Zepeng-Mu** [comment]
Well, this is a Pandas issue. The error is no longer there after updating to the latest version of Pandas.
Thanks!!

**Comment by pcarbo** [comment]
@Zepeng-Mu Can you tell us which version of pandas you were using, and which version you have now? Perhaps we can update the version requirements for pandas.

**Comment by Zepeng-Mu** [comment]
Hi, I am not sure about my previous pandas version before update, but now I am using 0.24.2.
According to documentation, `sort` argument is new in 0.23.0, so I assume this is the earliest version that can be used.
Thanks!

**Comment by gaow** [comment]
Thanks @Zepeng-Mu we officially release the pipeline using docker but it is good you caught the problem with your local setup. I will make 0.23.0 the minimum required version of pandas for the pipeline
