### ISSUE TITLE
estimate_null_correlation output changed?

### ISSUE THREAD

**Issue by Zepeng-Mu** [stephenslab/gtexresults#8]
Hi, I encountered another error when running the mashr_flashr workflow particularly at the following line:

https://github.com/stephenslab/gtexresults/blob/6e3cc6e3959f3de77a85d722cbd6b685e4c5670a/workflows/mashr_flashr_workflow.ipynb#L664

The error message says that $ can not be applied to atomic vectors.

Is this because in more recent version of mashr, the output of `estimate_null_correlation` function was changed from a list to `V` itself?

Thanks

**Comment by gaow** [comment]
@Zepeng-Mu yes indeed ... when you remove that line the problem will be fixed? 

The pipeline runs in a docker image which is now also obsolete. I'll have to update the docker image with latest `mashr` then fix this line; and test that everything works, before I push them to the repo. For the time being, if you are on the latest `mashr` could you fix it yourself for the moment? Thanks for letting us  know!

**Comment by Zepeng-Mu** [comment]
Thanks, I removed that and is re-running the script now. I think I should be fine.

**Comment by gaow** [comment]
Both docker image and the pipeline code have now been updated to using the latest mashr.
