### ISSUE TITLE
Fluctuating "Max cha(f)" 

### ISSUE THREAD

**Issue by heyuan7676** [stephenslab/gtexresults#9]
Hi!

Thank you for the detailed workflow! 

I'm using flashr in GTEx data to capture the latent factors with non-negative constraints. The data is a 49 x 17479 matrix, containing effect sizes from univariate eQTL studies across tissues (and not centered). I run flashr following the code in mashr_flashr_workflow.ipynb under workflows/, as shown below:
```r
 ebnm_fn = "ebnm_ash"
  ebnm_param = list(l = list(mixcompdist = "normal",
                             optmethod = "mixSQP"),
                    f = list(mixcompdist = "+uniform",
                             optmethod = "mixSQP"))
  ##
  fl_g <- flashr:::flash_greedy_workhorse(data,
                                          var_type = "constant",
                                          ebnm_fn = ebnm_fn,
                                          ebnm_param = ebnm_param,
                                          init_fn = "my_init_fn",
                                          stopping_rule = "factors",
                                          tol = 1e-3,
                                          verbose_output = "odF")
```

I got iterating updates as shown below. "Objective" jumps between -1836975.20 and -1836906.96 and "Max Chg (f)" keeps the same at 2.68e-03, and the run doesn't stop. 

Could you let me know if there are problems in my implementation (like in the input data)? Or do you have suggestions about whether I should increase tol or change stopping_rule in this situation? Thank you very much!

```
Fitting factor/loading 6 (stop when max factor change is < 1.00e-03):
  Iteration  Max Chg (f)      Objective   Obj Diff
          1     6.50e-02    -1839307.33        Inf
          2     4.20e-02    -1837492.59   1.81e+03
          3     2.43e-02    -1837196.73   2.96e+02
          4     2.22e-02    -1837066.56   1.30e+02
          5     1.83e-02    -1837006.18   6.04e+01
          6     9.56e-03    -1836976.74   2.94e+01
          7     4.12e-03    -1836961.83   1.49e+01
          8     2.70e-03    -1836953.91   7.92e+00
          9     2.18e-03    -1836949.40   4.51e+00
         10     1.34e-02    -1836946.63   2.77e+00
         11     1.26e-02    -1836944.61   2.02e+00
         12     1.97e-02    -1836950.68  -6.08e+00
         13     5.98e-03    -1836958.38  -7.70e+00
         14     5.04e-03    -1836965.75  -7.37e+00
         15     3.37e-03    -1836972.13  -6.39e+00
         16     2.40e-03    -1836977.57  -5.44e+00
         17     1.76e-03    -1836906.26   7.13e+01
         18     2.64e-03    -1836973.64  -6.74e+01
         19     2.76e-03    -1836981.07  -7.43e+00
         20     1.58e-03    -1836909.24   7.18e+01
         21     2.84e-03    -1836976.44  -6.72e+01
         22     2.43e-03    -1836907.49   6.90e+01
         23     2.69e-03    -1836975.42  -6.79e+01
         24     2.60e-03    -1836906.93   6.85e+01
         25     2.65e-03    -1836975.07  -6.81e+01
         26     2.66e-03    -1836906.77   6.83e+01
         27     2.64e-03    -1836975.00  -6.82e+01
         28     2.68e-03    -1836906.77   6.82e+01
         29     2.64e-03    -1836975.03  -6.83e+01
         30     2.69e-03    -1836906.81   6.82e+01
         31     2.65e-03    -1836975.09  -6.83e+01
         32     2.69e-03    -1836906.87   6.82e+01
         33     2.65e-03    -1836975.14  -6.83e+01
         34     2.68e-03    -1836906.92   6.82e+01
         35     2.66e-03    -1836975.20  -6.83e+01
         36     2.68e-03    -1836906.96   6.82e+01
```

**Comment by pcarbo** [comment]
@willwerscheid Could you offer any suggestions here? Maybe @heyuan7676 could try [flashier](https://github.com/willwerscheid/flashier)?

**Comment by stephens999** [comment]
looks like a bug...

Which version of mixsqp are you using? Can you make sure that is up to date
as a first step?
(As well as using the latest version of flashr and  ashr)

Matthew

**Comment by gaow** [comment]
@stephens999 @pcarbo I believe @heyuan7676 was using the versions in [the docker image](https://github.com/stephenslab/gtexresults/blob/master/workflows/mash.dockerfile) that we freeze for the GTEx analysis. Specifically, commit `a6b817e327fdc3f33fe06eb97da29958c9b3883f` for MixSQP and `f9407735986ae644ce0e60c4264d48dbc13f0b95` for flashr. Because @heyuan7676 touched base with me offline that using the current `master` of `flashr` and `MixSQP` failed even early on for this analysis. @heyuan7676  please verify. in the mean time, if you look into the pipeline there is a switch to use `mosek` : `--optmethod mixIP` instead. You can find how mosek is installed in our docker file:

https://github.com/stephenslab/gtexresults/blob/master/workflows/mash.dockerfile

However you'll need to obtain a license for it. See `sos run mashr_flashr_workflow.ipynb -h` for details.

On our end, possibly:

1. we need to make a separate rolling (updated over time) release in addition to the existing docker image so that we are both reproducible (with GTEx analysis) an up-to-date (reflecting latest state of mixSQP and flashier). 
2. figure out why current `master` of `flashr` and `mixSQP` dont work for this analysis.

**Comment by stephens999** [comment]
I don't really want to encourage people to use old versions of the
packages to generate new results!
It's fine to just reproduce old results, but any generation of new
results should be with latest package
versions. If the docker image is encouraging use of old versions of
packages we should rethink....

**Comment by heyuan7676** [comment]
Thank you for the comments! @pcarbo, @stephens999, @gaow. Yes I was following the versions from the docker container. However, < a6b817e327fdc3f33fe06eb97da29958c9b3883f > version of MixSQP failed to be installed, with the error <clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1>. mixsqp_0.2-2, flashr_0.6-3, and ashr_2.2-26 were used for this implementation. This can be the problem. Sorry I missed it, and thank you for your suggestions! 

Yes @gaow was right, when I was using the most updated versions for mixsqp, flashr, and ashr, I got the error:
<Error in match.arg(optmethod) : 
  'arg' should be one of “mixSQP”, “mixIP”, “cxxMixSquarem”, “mixEM”, “mixVBEM”, “w_mixEM” >.

**Comment by stephens999** [comment]
thanks, can you provide a reproducible example of the problem with the most
recent versions, including a small dataset?
(The error you got should not depend on the dataset you are using - it is a
syntax issue...)

**Comment by pcarbo** [comment]
@ heyuan7676 The specific error you got when trying to install the `mixsqp` package occurred because you don't have the proper C/C++ compilers installed in your system. What OS are you using?

Also, when submitting issues, sending the output from `sessionInfo()` can be very helpful!

**Comment by heyuan7676** [comment]
This is a bug on my end. I didn't replace the $optmethod in the workflow... It runs through now!!!

Just for reference, My sessionInfo() now is :

<
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ashr_2.2-39         Rmosek_8.0.69       Matrix_1.2-17       gridExtra_2.3       reshape2_1.4.3     
 [6] ggplot2_3.2.1       flashr_0.6-7        ROCR_1.0-7          gplots_3.0.1.1      limma_3.38.3       
[11] Biobase_2.42.0      BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         plyr_1.8.5         compiler_3.5.1     pillar_1.4.3       bitops_1.0-6      
 [6] iterators_1.0.12   tools_3.5.1        lifecycle_0.1.0    tibble_2.1.3       gtable_0.3.0      
[11] lattice_0.20-38    pkgconfig_2.0.3    rlang_0.4.2        foreach_1.4.7      rstudioapi_0.10   
[16] yaml_2.2.0         ebnm_0.1-24        withr_2.1.2        stringr_1.4.0      dplyr_0.8.3       
[21] gtools_3.8.1       caTools_1.17.1.2   tidyselect_0.2.5   grid_3.5.1         glue_1.3.1        
[26] R6_2.4.1           mixsqp_0.2-2       gdata_2.18.0       purrr_0.3.3        magrittr_1.5      
[31] scales_1.1.0       codetools_0.2-16   MASS_7.3-51.4      assertthat_0.2.1   softImpute_1.4    
[36] colorspace_1.4-1   KernSmooth_2.23-16 stringi_1.4.4      lazyeval_0.2.2     pscl_1.5.2        
[41] doParallel_1.0.15  munsell_0.5.0      truncnorm_1.0-8    SQUAREM_2017.10-1  crayon_1.3.4     
>

Thank you for all your suggestions!!!

**Comment by heyuan7676** [comment]
Following the previous post, I'm now using all updated packages. Thanks!

**Comment by gaow** [comment]
Thanks @heyuan7676 

@stephens999 @pcarbo what do you think of the following:

1. I make a release on the current github repo with current pipeline implementation that is compatible to the companion docker image
2. With @willwerscheid 's input I update the pipeline and docker directly to use latest `flashier` and also `mixSQP`？Or alternatively, stick to latest `flashr` and `mixSQP` not `flashier`?

Please let me know. I'll proceed per your suggestions.

**Comment by pcarbo** [comment]
Definitely 1.

**Comment by stephens999** [comment]
let's discuss in person - i'd like to understand your goal better.

**Comment by willwerscheid** [comment]
@gaow It's safest to stick with `flashr` -- there's not much advantage to `flashier` for a problem of this size.

**Comment by gaow** [comment]
Thanks @willwerscheid . 

@stephens999 the general approach is to use github release to freeze to some versions (can be automatically uploaded to zenodo as well upon release) with corresponding docker images. That's for reproducibility. We can discuss in person what do to with a rolling docker + workflow release, but for now I've updated docker images to use the current `master` of flashr, mixsqp, ashr and mashr.
